apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: {{ .Values.name }}
stringData:
  cakephp-secret-token: {{ .Values.cakephp_secret_token }}
  cakephp-security-salt: {{ .Values.cakephp_security_salt }}
  database-password: {{ .Values.database_password }}
  database-user: {{ .Values.database_user }}
