apiVersion: v1
kind: Secret
metadata:
  labels:
    app: dancer-mysql-persistent
    template: dancer-mysql-persistent
  name: {{ .Values.name }}
stringData:
  database-password: {{ .Values.database_password }}
  database-user: {{ .Values.database_user }}
  keybase: {{ .Values.secret_key_base }}
