apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.database_service_name }}",
      "kind": "Service"}]'
  labels:
    app: dancer-mysql-persistent
    template: dancer-mysql-persistent
  name: {{ .Values.name }}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  labels:
    app: dancer-mysql-persistent
    template: dancer-mysql-persistent
  name: {{ .Values.database_service_name }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    name: {{ .Values.database_service_name }}
