apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "postgresql-{{ .Values.image.version}}"
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "{{ .Values.image.repository }}-{{ .Values.image.version}}-rhel7:{{ .Values.image.tag }}"
      importPolicy:
        # periodically query registry to synchronize tag and image metadata
        scheduled: true
  lookupPolicy:
    local: true
