apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    template: valkey-persistent-template
  name: {{ .Values.database_service_name }}
stringData:
  database-password: {{ .Values.valkey_password }}
