apiVersion: v1
kind: Secret
metadata:
  labels:
    app: django-psql
    template: django-psql
  name: {{ .Values.name }}
stringData:
  database-password: {{ .Values.database_password }}
  database-user: {{ .Values.database_user }}
  django-secret-key: {{ .Values.django_secret_key }}
