apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: {{ .Values.name }}
spec:
  host: {{ .Values.application_domain }}
  tls:
    termiination: Edge
  to:
    kind: Service
    name: {{ .Values.name }}
