apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    app: django-psql
    template: django-psql
  name: {{ .Values.name }}
spec:
  {{ if .Values.registry.enabled }}
  output:
    to:
      kind: DockerImage
      name: "{{ .Values.registry.name }}/{{ .Values.registry.namespace }}/{{ .Values.name }}:latest"
    pushSecret:
      name: {{ .Values.registry.push_secret }}
  {{ else }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
  {{ end }}
  postCommit:
    script: ./manage.py test
  source:
    contextDir: {{ .Values.context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: PIP_INDEX_URL
        value: {{ .Values.pip_index_url }}
      from:
        kind: ImageStreamTag
        name: python:{{ .Values.python_version }}
        namespace: {{ .Values.namespace }}
    type: Source
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - github:
      secret: {{ .Values.github_webhook_secret }}
    type: GitHub
