apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: django-psql
    template: django-psql
  name: {{ .Values.database_service_name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume_capacity }}
