apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: django-psql-persistent
    template: django-psql-persistent
  name: {{ .Values.name }}
spec:
  host: {{ .Values.application_domain }}
  to:
    kind: Service
    name: {{ .Values.name }}
