apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.database_service_name }}",
      "kind": "Service"}]'
  labels:
    app: django-psql-persistent
    template: django-psql-persistent
  name: {{ .Values.name }}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  labels:
    app: django-psql-persistent
    template: django-psql-persistent
  name: {{ .Values.database_service_name }}
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    name: {{ .Values.database_service_name }}
