description: |-
  PostgreSQL database service imagestreams. For more information about PostgreSQL container see https://github.com/sclorg/postgresql-container/.

name: postgresql-imagestreams
tags: database,postgresql
sources:
  - https://github.com/sclorg/helm-charts
version: v0.0.1
