apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Valkey
  name: valkey
spec:
  tags:
    - annotations:
        description: >-
          Provides a Valkey 8 database on CentOS Stream 10. For more information
          about using this database image, including OpenShift considerations, see 
          https://github.com/sclorg/valkey-container/tree/master/8/README.md.

          WARNING: By selecting this tag, your application will automatically 
          update to use the latest version of Valkey available on OpenShift, 
          including major version updates.
        iconClass: icon-valkey
        openshift.io/display-name: Valkey (Latest)
        openshift.io/provider-display-name: Red Hat, Inc.
        tags: valkey
      from:
        kind: ImageStreamTag
        name: 8-c10s
      referencePolicy:
        type: Local
      name: latest
    - annotations:
        description: >-
          Provides a Valkey 8 database on CentOS Stream 10. For more information about 
          using this database image, including OpenShift considerations, see 
          https://github.com/sclorg/valkey-container/tree/master/8/README.md.
        iconClass: icon-valkey
        openshift.io/display-name: Valkey 8 (CentOS Stream 10)
        openshift.io/provider-display-name: Red Hat, Inc.
        tags: valkey
        version: "8"
      from:
        kind: DockerImage
        name: quay.io/sclorg/valkey-8-c10s:latest
      referencePolicy:
        type: Local
      name: 8-el10
