apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    app: httpd-example
    template: httpd-example
  name: {{ .Values.name }}
spec:
  {{ if .Values.registry.enabled }}
  output:
    to:
      kind: DockerImage
      name: "{{ .Values.registry.name }}/{{ .Values.registry.namespace }}/{{ .Values.name }}:latest"
    pushSecret:
      name: images-paas-push-config
  {{ else }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
  {{ end }}
  source:
    contextDir: {{ .Values.context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:{{ .Values.httpd_version }}
    type: Source
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secret: {{ .Values.github_webhook_secret }}
  - type: Generic
    generic:
      secret: {{ .Values.generic_webhook_secret }}
