on:
  issue_comment:
    types:
      - created
jobs:
  openshift-tests:
    # This job only runs for '[test]' pull request comments by owner, member
    name: "Integration tests for Helm charts ${{ matrix.helm_chart }} tested on RHEL-8 OpenShift 4"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        helm_chart: ["httpd", "mariadb", "mysql", "nginx", "postgresql", "redis", "php", "perl", "nodejs", "ruby", "python"]

    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"

      - name: Schedule tests on external Testing Farm by Testing-Farm-as-github-action
        uses: sclorg/testing-farm-as-github-action@main
        with:
          api_key:  ${{ secrets.TF_INTERNAL_API_KEY }}
          compose:  "RHEL-8.10.0-Nightly"
          git_url:  "https://gitlab.cee.redhat.com/platform-eng-core-services/sclorg-tmt-plans"
          git_ref:  "master"
          tf_scope: "private"
          tmt_plan_regex: "rhel8-openshift-helms"
          update_pull_request_status: true
          pull_request_status_name: "Helm chart - ${{ matrix.helm_chart }}"
          variables: "REPO_URL=${{ github.server_url }}/${{ github.repository }};REPO_NAME=${{ github.repository }};PR_NUMBER=${{ github.event.issue.number }};TEST_NAME=test-${{ matrix.helm_chart }}"
